"""Static Chinese name mapping for common higher taxonomy ranks.

Used as the final fallback when Wikidata and TaiCOL don't return Chinese names.
These are standard biological taxonomy terms in Traditional Chinese (繁體中文).
"""

# Maps: English taxonomy name → Traditional Chinese name
# Organized by rank for clarity, but stored in a single flat dict for lookup.

TAXONOMY_ZH = {
    # --- Kingdom 界 ---
    'Animalia': '動物界',
    'Plantae': '植物界',
    'Fungi': '真菌界',
    'Chromista': '原藻界',
    'Protozoa': '原生動物界',
    'Bacteria': '細菌界',
    'Archaea': '古菌界',
    'Viruses': '病毒界',

    # --- Phylum 門 ---
    'Chordata': '脊索動物門',
    'Arthropoda': '節肢動物門',
    'Mollusca': '軟體動物門',
    'Annelida': '環節動物門',
    'Cnidaria': '刺胞動物門',
    'Echinodermata': '棘皮動物門',
    'Nematoda': '線蟲動物門',
    'Platyhelminthes': '扁形動物門',
    'Porifera': '多孔動物門',
    'Bryophyta': '苔蘚植物門',
    'Pteridophyta': '蕨類植物門',
    'Magnoliophyta': '被子植物門',
    'Tracheophyta': '維管束植物門',
    'Coniferophyta': '松柏門',
    'Basidiomycota': '擔子菌門',
    'Ascomycota': '子囊菌門',
    'Rotifera': '輪蟲動物門',
    'Tardigrada': '緩步動物門',
    'Ctenophora': '櫛水母動物門',
    'Chaetognatha': '毛顎動物門',

    # --- Class 綱 ---
    'Mammalia': '哺乳綱',
    'Aves': '鳥綱',
    'Reptilia': '爬蟲綱',
    'Amphibia': '兩棲綱',
    'Actinopterygii': '條鰭魚綱',
    'Chondrichthyes': '軟骨魚綱',
    'Insecta': '昆蟲綱',
    'Arachnida': '蛛形綱',
    'Malacostraca': '軟甲綱',
    'Gastropoda': '腹足綱',
    'Bivalvia': '雙殼綱',
    'Cephalopoda': '頭足綱',
    'Myxini': '盲鰻綱',
    'Petromyzonti': '七鰓鰻綱',
    'Sarcopterygii': '肉鰭魚綱',
    'Holocephali': '全頭亞綱',
    'Magnoliopsida': '木蘭綱',
    'Liliopsida': '百合綱',
    'Pinopsida': '松綱',
    'Polypodiopsida': '水龍骨綱',
    'Agaricomycetes': '傘菌綱',

    # --- Order 目 ---
    'Carnivora': '食肉目',
    'Primates': '靈長目',
    'Rodentia': '齧齒目',
    'Chiroptera': '翼手目',
    'Cetacea': '鯨目',
    'Artiodactyla': '偶蹄目',
    'Perissodactyla': '奇蹄目',
    'Proboscidea': '長鼻目',
    'Lagomorpha': '兔形目',
    'Marsupialia': '有袋目',
    'Monotremata': '單孔目',
    'Insectivora': '食蟲目',
    'Xenarthra': '貧齒目',
    'Sirenia': '海牛目',
    'Pinnipedia': '鰭足目',
    'Passeriformes': '雀形目',
    'Accipitriformes': '鷹形目',
    'Falconiformes': '隼形目',
    'Strigiformes': '鴞形目',
    'Psittaciformes': '鸚形目',
    'Columbiformes': '鴿形目',
    'Anseriformes': '雁形目',
    'Galliformes': '雞形目',
    'Pelecaniformes': '鵜形目',
    'Charadriiformes': '鴴形目',
    'Piciformes': '鴷形目',
    'Coraciiformes': '佛法僧目',
    'Squamata': '有鱗目',
    'Testudines': '龜鱉目',
    'Crocodilia': '鱷目',
    'Anura': '無尾目',
    'Caudata': '有尾目',
    'Perciformes': '鱸形目',
    'Cypriniformes': '鯉形目',
    'Siluriformes': '鯰形目',
    'Salmoniformes': '鮭形目',
    'Coleoptera': '鞘翅目',
    'Lepidoptera': '鱗翅目',
    'Hymenoptera': '膜翅目',
    'Diptera': '雙翅目',
    'Hemiptera': '半翅目',
    'Orthoptera': '直翅目',
    'Odonata': '蜻蛉目',
    'Decapoda': '十足目',
    'Araneae': '蜘蛛目',
    'Scorpiones': '蠍目',

    # --- Family 科 ---
    'Felidae': '貓科',
    'Canidae': '犬科',
    'Ursidae': '熊科',
    'Mustelidae': '鼬科',
    'Procyonidae': '浣熊科',
    'Herpestidae': '獴科',
    'Viverridae': '靈貓科',
    'Hyaenidae': '鬣狗科',
    'Ailuridae': '小貓熊科',
    'Otariidae': '海獅科',
    'Phocidae': '海豹科',
    'Cervidae': '鹿科',
    'Bovidae': '牛科',
    'Suidae': '豬科',
    'Equidae': '馬科',
    'Elephantidae': '象科',
    'Rhinocerotidae': '犀牛科',
    'Hippopotamidae': '河馬科',
    'Giraffidae': '長頸鹿科',
    'Camelidae': '駱駝科',
    'Delphinidae': '海豚科',
    'Balaenopteridae': '鬚鯨科',
    'Hominidae': '人科',
    'Cercopithecidae': '獼猴科',
    'Lemuridae': '狐猴科',
    'Leporidae': '兔科',
    'Muridae': '鼠科',
    'Sciuridae': '松鼠科',
    'Castoridae': '河狸科',
    'Accipitridae': '鷹科',
    'Falconidae': '隼科',
    'Strigidae': '鴟鴞科',
    'Tytonidae': '草鴞科',
    'Psittacidae': '鸚鵡科',
    'Corvidae': '鴉科',
    'Columbidae': '鴿科',
    'Anatidae': '雁鴨科',
    'Phasianidae': '雉科',
    'Viperidae': '蝰科',
    'Elapidae': '蝙蝠蛇科',
    'Colubridae': '黃頷蛇科',
    'Pythonidae': '蟒科',
    'Boidae': '蚺科',
    'Testudinidae': '陸龜科',
    'Cheloniidae': '海龜科',
    'Crocodylidae': '鱷科',
    'Gekkonidae': '壁虎科',
    'Scincidae': '石龍子科',
    'Ranidae': '蛙科',
    'Bufonidae': '蟾蜍科',
    'Salamandridae': '蠑螈科',
    'Salmonidae': '鮭科',
    'Cyprinidae': '鯉科',
    'Cichlidae': '慈鯛科',
    'Scarabaeidae': '金龜子科',
    'Cerambycidae': '天牛科',
    'Coccinellidae': '瓢蟲科',
    'Nymphalidae': '蛺蝶科',
    'Papilionidae': '鳳蝶科',
    'Pieridae': '粉蝶科',
    'Apidae': '蜜蜂科',
    'Formicidae': '蟻科',
    'Vespidae': '胡蜂科',
    'Culicidae': '蚊科',
    'Muscidae': '家蠅科',
    'Araneidea': '園蛛科',
    'Theraphosidae': '捕鳥蛛科',
    'Nephilidae': '絡新婦科',

    # --- Genus 屬 (common ones) ---
    # Mammals - Carnivora
    'Felis': '貓屬',
    'Panthera': '豹屬',
    'Lynx': '猞猁屬',
    'Acinonyx': '獵豹屬',
    'Neofelis': '雲豹屬',
    'Prionailurus': '豹貓屬',
    'Canis': '犬屬',
    'Vulpes': '狐屬',
    'Nyctereutes': '貉屬',
    'Ursus': '熊屬',
    'Ailuropoda': '大貓熊屬',
    'Ailurus': '小貓熊屬',
    'Lutra': '水獺屬',
    'Mustela': '鼬屬',
    'Meles': '獾屬',
    'Martes': '貂屬',
    'Procyon': '浣熊屬',
    'Herpestes': '獴屬',
    'Paguma': '果子狸屬',
    'Crocuta': '斑鬣狗屬',
    # Mammals - Primates
    'Homo': '人屬',
    'Pan': '黑猩猩屬',
    'Gorilla': '大猩猩屬',
    'Pongo': '紅毛猩猩屬',
    'Macaca': '獼猴屬',
    # Mammals - Ungulates
    'Equus': '馬屬',
    'Bos': '牛屬',
    'Bubalus': '水牛屬',
    'Sus': '豬屬',
    'Ovis': '羊屬',
    'Capra': '山羊屬',
    'Cervus': '鹿屬',
    'Muntiacus': '麂屬',
    'Giraffa': '長頸鹿屬',
    'Hippopotamus': '河馬屬',
    'Camelus': '駱駝屬',
    'Lama': '駱馬屬',
    # Mammals - Marine
    'Tursiops': '瓶鼻海豚屬',
    'Orcinus': '虎鯨屬',
    'Phoca': '海豹屬',
    'Zalophus': '海獅屬',
    'Dugong': '儒艮屬',
    # Mammals - Others
    'Elephas': '象屬',
    'Loxodonta': '非洲象屬',
    'Rhinoceros': '犀牛屬',
    'Oryctolagus': '穴兔屬',
    'Lepus': '兔屬',
    'Rattus': '鼠屬',
    'Mus': '小鼠屬',
    'Sciurus': '松鼠屬',
    'Castor': '河狸屬',
    'Pteropus': '狐蝠屬',
    'Erinaceus': '蝟屬',
    # Birds
    'Aquila': '鵰屬',
    'Haliaeetus': '海鵰屬',
    'Milvus': '鳶屬',
    'Buteo': '鵟屬',
    'Accipiter': '鷹屬',
    'Falco': '隼屬',
    'Strix': '林鴞屬',
    'Bubo': '鵰鴞屬',
    'Corvus': '鴉屬',
    'Pica': '鵲屬',
    'Passer': '麻雀屬',
    'Hirundo': '燕屬',
    'Columba': '鴿屬',
    'Gallus': '原雞屬',
    'Pavo': '孔雀屬',
    'Anas': '鴨屬',
    'Cygnus': '天鵝屬',
    'Phoenicopterus': '紅鶴屬',
    'Psittacus': '灰鸚鵡屬',
    'Ara': '金剛鸚鵡屬',
    'Phasianus': '雉屬',
    'Spheniscus': '環企鵝屬',
    'Aptenodytes': '王企鵝屬',
    # Reptiles
    'Python': '蟒屬',
    'Naja': '眼鏡蛇屬',
    'Crocodylus': '鱷屬',
    'Alligator': '短吻鱷屬',
    'Testudo': '陸龜屬',
    'Chelonia': '海龜屬',
    'Varanus': '巨蜥屬',
    'Iguana': '鬣蜥屬',
    'Gecko': '壁虎屬',
    'Chamaeleo': '變色龍屬',
    # Amphibians
    'Rana': '蛙屬',
    'Bufo': '蟾蜍屬',
    'Salamandra': '蠑螈屬',
    'Ambystoma': '鈍口螈屬',
    # Fish
    'Danio': '斑馬魚屬',
    'Salmo': '鮭屬',
    'Oncorhynchus': '太平洋鮭屬',
    'Carassius': '鯽屬',
    'Cyprinus': '鯉屬',
    'Thunnus': '鮪屬',
    'Hippocampus': '海馬屬',
    # Invertebrates
    'Apis': '蜜蜂屬',
    'Bombyx': '蠶屬',
    'Papilio': '鳳蝶屬',
    'Octopus': '章魚屬',
    'Sepia': '烏賊屬',
}


def get_taxonomy_zh(name):
    """Look up the Chinese name for a taxonomy term.

    Args:
        name: English taxonomy name (e.g. 'Mammalia', 'Felidae')

    Returns:
        Chinese name string or None if not found.
    """
    return TAXONOMY_ZH.get(name)


def get_taxonomy_zh_for_ranks(kingdom=None, phylum=None, class_=None,
                               order=None, family=None, genus=None):
    """Get Chinese names for all provided taxonomy ranks.

    Returns dict with keys like 'kingdom_zh', 'phylum_zh', etc.
    """
    result = {}
    for field, value in [
        ('kingdom', kingdom),
        ('phylum', phylum),
        ('class', class_),
        ('order', order),
        ('family', family),
        ('genus', genus),
    ]:
        if value:
            result[f'{field}_zh'] = TAXONOMY_ZH.get(value)
        else:
            result[f'{field}_zh'] = None
    return result
