// Static country data with Traditional Chinese names
// Common countries are placed first for convenience

const COUNTRIES = [
  { code: 'TW', name: '台灣' },
  { code: 'JP', name: '日本' },
  { code: 'US', name: '美國' },
  { code: 'KR', name: '韓國' },
  { code: 'GB', name: '英國' },
  { code: 'CA', name: '加拿大' },
  { code: 'AU', name: '澳洲' },
  { code: 'DE', name: '德國' },
  { code: 'FR', name: '法國' },
  { code: 'CN', name: '中國' },
  { code: 'HK', name: '香港' },
  { code: 'SG', name: '新加坡' },
  { code: 'MY', name: '馬來西亞' },
  { code: 'TH', name: '泰國' },
  { code: 'PH', name: '菲律賓' },
  { code: 'ID', name: '印尼' },
  { code: 'VN', name: '越南' },
  { code: 'IN', name: '印度' },
  { code: 'BR', name: '巴西' },
  { code: 'MX', name: '墨西哥' },
  { code: 'AR', name: '阿根廷' },
  { code: 'CL', name: '智利' },
  { code: 'CO', name: '哥倫比亞' },
  { code: 'PE', name: '秘魯' },
  { code: 'ES', name: '西班牙' },
  { code: 'IT', name: '義大利' },
  { code: 'PT', name: '葡萄牙' },
  { code: 'NL', name: '荷蘭' },
  { code: 'BE', name: '比利時' },
  { code: 'CH', name: '瑞士' },
  { code: 'AT', name: '奧地利' },
  { code: 'SE', name: '瑞典' },
  { code: 'NO', name: '挪威' },
  { code: 'DK', name: '丹麥' },
  { code: 'FI', name: '芬蘭' },
  { code: 'PL', name: '波蘭' },
  { code: 'CZ', name: '捷克' },
  { code: 'HU', name: '匈牙利' },
  { code: 'RO', name: '羅馬尼亞' },
  { code: 'GR', name: '希臘' },
  { code: 'TR', name: '土耳其' },
  { code: 'RU', name: '俄羅斯' },
  { code: 'UA', name: '烏克蘭' },
  { code: 'IL', name: '以色列' },
  { code: 'SA', name: '沙烏地阿拉伯' },
  { code: 'AE', name: '阿拉伯聯合大公國' },
  { code: 'EG', name: '埃及' },
  { code: 'ZA', name: '南非' },
  { code: 'NG', name: '奈及利亞' },
  { code: 'KE', name: '肯亞' },
  { code: 'NZ', name: '紐西蘭' },
  { code: 'IE', name: '愛爾蘭' },
  { code: 'IS', name: '冰島' },
  { code: 'MM', name: '緬甸' },
  { code: 'KH', name: '柬埔寨' },
  { code: 'LA', name: '寮國' },
  { code: 'NP', name: '尼泊爾' },
  { code: 'LK', name: '斯里蘭卡' },
  { code: 'BD', name: '孟加拉' },
  { code: 'PK', name: '巴基斯坦' },
  { code: 'MN', name: '蒙古' },
  { code: 'KP', name: '北韓' },
  { code: 'HR', name: '克羅埃西亞' },
  { code: 'RS', name: '塞爾維亞' },
  { code: 'BG', name: '保加利亞' },
  { code: 'SK', name: '斯洛伐克' },
  { code: 'SI', name: '斯洛維尼亞' },
  { code: 'LT', name: '立陶宛' },
  { code: 'LV', name: '拉脫維亞' },
  { code: 'EE', name: '愛沙尼亞' },
  { code: 'LU', name: '盧森堡' },
  { code: 'MT', name: '馬爾他' },
  { code: 'CY', name: '賽普勒斯' },
  { code: 'PA', name: '巴拿馬' },
  { code: 'CR', name: '哥斯大黎加' },
  { code: 'CU', name: '古巴' },
  { code: 'JM', name: '牙買加' },
  { code: 'DO', name: '多明尼加' },
  { code: 'EC', name: '厄瓜多' },
  { code: 'VE', name: '委內瑞拉' },
  { code: 'UY', name: '烏拉圭' },
  { code: 'PY', name: '巴拉圭' },
  { code: 'BO', name: '玻利維亞' },
  { code: 'MA', name: '摩洛哥' },
  { code: 'TN', name: '突尼西亞' },
  { code: 'DZ', name: '阿爾及利亞' },
  { code: 'GH', name: '迦納' },
  { code: 'ET', name: '衣索比亞' },
  { code: 'TZ', name: '坦尚尼亞' },
  { code: 'QA', name: '卡達' },
  { code: 'KW', name: '科威特' },
  { code: 'OM', name: '阿曼' },
  { code: 'BH', name: '巴林' },
  { code: 'JO', name: '約旦' },
  { code: 'LB', name: '黎巴嫩' },
  { code: 'IQ', name: '伊拉克' },
  { code: 'IR', name: '伊朗' },
  { code: 'AF', name: '阿富汗' },
  { code: 'GE', name: '喬治亞' },
  { code: 'AM', name: '亞美尼亞' },
  { code: 'AZ', name: '亞塞拜然' },
  { code: 'KZ', name: '哈薩克' },
  { code: 'UZ', name: '烏茲別克' },
];

export default COUNTRIES;

const countryMap = new Map(COUNTRIES.map(c => [c.code, c.name]));

export function getCountryName(code) {
  return countryMap.get(code?.toUpperCase()) || code;
}
